[server]
threads = -1
datadir = /var/lib/snapserver

[http]
enabled = true
port = 1780
doc_root = /usr/share/snapserver/snapweb

[tcp-control]
enabled = true
port = 1705

[tcp-streaming]
port = 1704

[stream]
source = pipe:///snapfifo/snapfifo?name=YouTube&sampleformat=48000:16:2&codec=pcm
